"""Markdown risk report: VaR/ES table, decomposition, volatility, backtest."""
from __future__ import annotations

from datetime import date

import pandas as pd

from .backtest import TestResult
from .var import VarSummary


def _pct(x: float) -> str:
    return f"{x * 100:.3f}%"


def build_report(summary: VarSummary, decomposition: pd.DataFrame,
                 garch_info: dict, backtest_info: dict,
                 portfolio_desc: str) -> str:
    a = int(summary.alpha * 100)
    lines = [
        f"# Market Risk Report — {date.today().isoformat()}",
        "",
        f"Portfolio: {portfolio_desc}",
        f"Confidence level: **{a}%**, one-day horizon. VaR/ES quoted as a "
        "fraction of portfolio value (positive = loss).",
        "",
        "## VaR / ES by method",
        "",
        "| Method | Value |",
        "|---|---|",
    ]
    lines += [f"| {k} | {_pct(v)} |" for k, v in summary.as_dict().items()]

    lines += [
        "",
        "## Risk decomposition (component VaR, Euler allocation)",
        "",
        "| Asset | Weight | Marginal VaR | Component VaR | % of total |",
        "|---|---|---|---|---|",
    ]
    for name, row in decomposition.iterrows():
        lines.append(
            f"| {name} | {row['weight']:.2f} | {_pct(row['marginal_var'])} "
            f"| {_pct(row['component_var'])} | {row['pct_of_total'] * 100:.1f}% |")
    lines.append(f"| **Total** |  |  | **{_pct(decomposition.attrs['total_var'])}** | 100% |")

    lines += [
        "",
        "## Volatility (GARCH(1,1), normal MLE)",
        "",
        f"- omega={garch_info['omega']:.3e}, alpha={garch_info['alpha']:.3f}, "
        f"beta={garch_info['beta']:.3f} → persistence **{garch_info['persistence']:.3f}**",
        f"- Long-run daily vol: {_pct(garch_info['long_run_vol'])}; "
        f"current: {_pct(garch_info['current_vol'])}",
        "",
        "## VaR backtest (rolling out-of-sample)",
        "",
        f"- Window: {backtest_info['window']} days, method: {backtest_info['method']}",
        f"- Violations: **{backtest_info['observed_violations']}** observed vs "
        f"{backtest_info['expected_violations']} expected "
        f"({backtest_info['n_out']} out-of-sample days)",
        f"- Basel traffic light (last 250d): **{backtest_info['traffic_light']['zone'].upper()}** "
        f"({backtest_info['traffic_light']['violations']} breaches)",
        "",
        "| Test | LR statistic | p-value | Reject at 5%? |",
        "|---|---|---|---|",
    ]
    for t in backtest_info["tests"]:
        assert isinstance(t, TestResult)
        lines.append(f"| {t.name} | {t.statistic:.3f} | {t.p_value:.3f} "
                     f"| {'YES' if t.reject_95 else 'no'} |")

    lines += [
        "",
        "---",
        "*Generated by `marketrisk` — historical / parametric / Cornish-Fisher / "
        "Monte Carlo VaR & ES, GARCH volatility, Euler risk decomposition, and "
        "Kupiec / Christoffersen / Basel backtesting.*",
        "",
    ]
    return "\n".join(lines)
